/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vue;

import Controller.connexion.ClientController;
import Modele.Adresse;
import Modele.Client;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;



/**
 *
 * @author Carmelle Adou
 */
public class FormClient extends javax.swing.JDialog {
    private ClientController clientController;
    private Client client;
   


    /**
     * Creates new form FormClient
     */
    public FormClient(java.awt.Frame parent, boolean modal, Client client) {
        super(parent, modal);
        initComponents();
        this.clientController = new ClientController();
        this.client = client;
        
        if (client != null) {
            jTextFieldNom.setText(client.getNom());
            jTextFieldPrenom.setText(client.getPrenom());
            jTextFielduser.setText(client.getEmail());
            jTextFieldGSM.setText(client.getTelephone());

            Adresse adresse = client.getAdresse();
            if (adresse != null) {
                jTextFieldRue.setText(adresse.getRue());
                jTextFieldCodePostal.setText(adresse.getCodePostal());
                jTextFieldVille.setText(adresse.getVille());
            }
        }

        jBtnEnreg.addActionListener(evt -> enregistrerClient());
        jBtnAnnuler.addActionListener(evt -> this.dispose());
    }
    
    private void enregistrerClient() {
        String nom = jTextFieldNom.getText().trim();
        String prenom = jTextFieldPrenom.getText().trim();
        String email = jTextFielduser.getText().trim();
        String telephone = jTextFieldGSM.getText().trim();
        String rue = jTextFieldRue.getText().trim();
        String ville = jTextFieldVille.getText().trim();
        String codePostal = jTextFieldCodePostal.getText().trim();
        String dateText = jTextFieldDateNaissance.getText().trim(); // ✅ Champ date

        if (nom.isEmpty() || prenom.isEmpty() || email.isEmpty() || telephone.isEmpty() ||
            rue.isEmpty() || ville.isEmpty() || codePostal.isEmpty() || dateText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis !");
            return;
        }

        // ✅ Conversion de la date avec validation
        java.sql.Date dateNaissance = null;
        try {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            format.setLenient(false); // Empêche les erreurs comme 30 février
            java.util.Date parsedDate = format.parse(dateText);
            dateNaissance = new java.sql.Date(parsedDate.getTime());

            // ✅ Vérification : Affichage de la date convertie
            System.out.println("Date de naissance convertie : " + dateNaissance);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Format de date invalide ! Utilisez : yyyy-MM-dd", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Adresse adresse = new Adresse(0, rue, ville, codePostal);
            if (client == null) {
                // ✅ Vérification avant l'ajout
                System.out.println("Ajout d'un nouveau client : " + nom + " " + prenom + ", Date de naissance : " + dateNaissance);

                clientController.ajouterClient(new Client(0, nom, prenom, email, telephone, adresse, dateNaissance));
            } else {
                // ✅ Mise à jour des valeurs du client
                
                client.setNom(nom);
                client.setPrenom(prenom);
                client.setEmail(email);
                client.setTelephone(telephone);
                client.setAdresse(adresse);

                // ✅ Vérification avant modification
                System.out.println("Modification du client : " + nom + " " + prenom + ", Nouvelle date : " + dateNaissance);

                clientController.modifierClient(client);
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'enregistrement : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldDateNaissance = new javax.swing.JTextField();
        jTextFieldGSM = new javax.swing.JTextField();
        jTextFieldRue = new javax.swing.JTextField();
        jLabelDateNaissance = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabeltelephone = new javax.swing.JLabel();
        jLabelrue = new javax.swing.JLabel();
        jLabelCodePostal = new javax.swing.JLabel();
        jTextFieldCodePostal = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jLabelville = new javax.swing.JLabel();
        jBtnEnreg = new javax.swing.JButton();
        jBtnAnnuler = new javax.swing.JButton();
        jTextFielduser = new javax.swing.JTextField();
        jLabelid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 12, 300, -1));
        getContentPane().add(jTextFieldPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 70, 300, -1));
        getContentPane().add(jTextFieldDateNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 137, 200, -1));
        getContentPane().add(jTextFieldGSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 184, 210, -1));
        getContentPane().add(jTextFieldRue, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 258, 220, -1));

        jLabelDateNaissance.setText("Date de naissance : ");
        getContentPane().add(jLabelDateNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 137, -1, -1));

        jLabelPrenom.setText("Prenom :");
        getContentPane().add(jLabelPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 70, -1, -1));

        jLabelNom.setText("Nom :");
        getContentPane().add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 15, -1, -1));

        jLabeltelephone.setText("GSM : ");
        getContentPane().add(jLabeltelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 184, -1, -1));

        jLabelrue.setText("Rue :");
        getContentPane().add(jLabelrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 231, -1, -1));

        jLabelCodePostal.setText("Code Postal : ");
        getContentPane().add(jLabelCodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 321, -1, -1));
        getContentPane().add(jTextFieldCodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 318, 153, -1));
        getContentPane().add(jTextFieldVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 358, 153, -1));

        jLabelville.setText("ville : ");
        getContentPane().add(jLabelville, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 361, -1, -1));

        jBtnEnreg.setText("Enregister");
        getContentPane().add(jBtnEnreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, 45));

        jBtnAnnuler.setText("Annuler");
        getContentPane().add(jBtnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 470, 112, 45));
        getContentPane().add(jTextFielduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 221, -1));

        jLabelid.setText("Identifiant :");
        getContentPane().add(jLabelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 43, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormClient dialog = new FormClient(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnnuler;
    private javax.swing.JButton jBtnEnreg;
    private javax.swing.JLabel jLabelCodePostal;
    private javax.swing.JLabel jLabelDateNaissance;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelrue;
    private javax.swing.JLabel jLabeltelephone;
    private javax.swing.JLabel jLabelville;
    private javax.swing.JTextField jTextFieldCodePostal;
    private javax.swing.JTextField jTextFieldDateNaissance;
    private javax.swing.JTextField jTextFieldGSM;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldRue;
    private javax.swing.JTextField jTextFieldVille;
    private javax.swing.JTextField jTextFielduser;
    // End of variables declaration//GEN-END:variables
}
