/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Modele.Users;
import crud.UsersCRUD;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;


/**
 *
 * @author Carmelle Adou
 */
public class PageAdmin extends javax.swing.JFrame {

    private UsersCRUD usersCRUD;
    private boolean isGestionUsers = true; // Permet de basculer entre Users et Employés
    private TableRowSorter<DefaultTableModel> rowSorter;
    private DefaultTableModel tableModel;
    private javax.swing.JFrame previousPage;

    /**
     * Creates new form PageAdmin
     */
    public PageAdmin(javax.swing.JFrame previousPage) {
        this.previousPage = previousPage;
        initComponents();
        this.usersCRUD = new UsersCRUD();
        chargerUtilisateurs();
        initListeners();
        
    }
    
    private void initListeners() {
        jBtnAdd.addActionListener(evt -> ajouterUtilisateur());
        jbtnUpdate.addActionListener(evt -> modifierUtilisateur());
        jbtnDelete.addActionListener(evt -> supprimerUtilisateur());
        jbtnQuitter.addActionListener(evt -> System.exit(0));
        jbtnConfigDB.addActionListener(evt -> ouvrirConfigDB());
        jBtnretour.addActionListener(evt -> retournerPagePrecedente());

        
        // Écouteur pour le menu déroulant
        itemClient.addActionListener(evt -> ouvrirNouvellePage(new PageEmploye(this)));
        itemStock.addActionListener(evt -> ouvrirNouvellePage(new PageStocks(this)));
        itemVente.addActionListener(evt -> {
            try {
                ouvrirNouvellePage(new PageVente());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PageAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        // Écouteur pour la barre de recherche
        jbtnsearch.addActionListener(evt -> rechercherUtilisateur());
        
    }
    private void ouvrirConfigDB() {
        new PageConfig(this, true).setVisible(true);
    }

    private void ouvrirNouvellePage(javax.swing.JFrame nouvellePage) {
        nouvellePage.setVisible(true);
        this.dispose();
    }
    
    private void retournerPagePrecedente() {
        if (previousPage != null) {
            System.out.println("Retour à la page précédente : " + previousPage.getClass().getSimpleName()); // Debug
            previousPage.setVisible(true);
        } else {
            System.out.println("Impossible de retourner, aucune page précédente enregistrée !");
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jLabelGestionCpt = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jBtnAdd = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnQuitter = new javax.swing.JButton();
        button1 = new java.awt.Button();
        jbtnConfigDB = new javax.swing.JButton();
        jTextFieldsearch = new javax.swing.JTextField();
        jbtnsearch = new javax.swing.JButton();
        jBtnretour = new javax.swing.JButton();
        jMenuGestion = new javax.swing.JMenuBar();
        jMenuGerer = new javax.swing.JMenu();
        itemClient = new javax.swing.JMenuItem();
        itemStock = new javax.swing.JMenuItem();
        itemVente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "identifiant", "Nom", "Prenom", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(jTableUsers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 660, 220));

        jLabelGestionCpt.setBackground(new java.awt.Color(255, 255, 255));
        jLabelGestionCpt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelGestionCpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageGesCpt.png"))); // NOI18N
        jLabelGestionCpt.setText("Gestion Admin");
        getContentPane().add(jLabelGestionCpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, 110));

        panel1.setBackground(new java.awt.Color(0, 51, 102));

        jBtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgAdd.png"))); // NOI18N
        jBtnAdd.setText("Ajouter");

        jbtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgmodif.png"))); // NOI18N
        jbtnUpdate.setText("Modifier");

        jbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgsupp.png"))); // NOI18N
        jbtnDelete.setText("Supprimer");

        jbtnQuitter.setText("Quitter");

        button1.setLabel("button1");

        jbtnConfigDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgreglages.png"))); // NOI18N
        jbtnConfigDB.setText("Config BD");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jbtnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnConfigDB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jbtnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBtnAdd)
                .addGap(18, 18, 18)
                .addComponent(jbtnUpdate)
                .addGap(43, 43, 43)
                .addComponent(jbtnDelete)
                .addGap(72, 72, 72)
                .addComponent(jbtnConfigDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jbtnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 440));
        getContentPane().add(jTextFieldsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 230, 30));

        jbtnsearch.setText("search");
        getContentPane().add(jbtnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 90, 30));

        jBtnretour.setText("Retour");
        getContentPane().add(jBtnretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        jMenuGerer.setText("Gestion");

        itemClient.setText("Gestion Clients");
        jMenuGerer.add(itemClient);

        itemStock.setText("Gestion Stocks");
        jMenuGerer.add(itemStock);

        itemVente.setText("Gestion Ventes");
        jMenuGerer.add(itemVente);

        jMenuGestion.add(jMenuGerer);

        setJMenuBar(jMenuGestion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chargerUtilisateurs() {
        try {
            //System.out.println("📌 Chargement des utilisateurs..."); // Debug

            List<Users> listeUsers = usersCRUD.getAllUsersWithEmployes();
            tableModel = (DefaultTableModel) jTableUsers.getModel(); // Initialisation du modèle
            tableModel.setRowCount(0);

            if (listeUsers.isEmpty()) {
                System.out.println("❌ Aucun utilisateur trouvé !");
            } else {
                for (Users user : listeUsers) {
                    //System.out.println("📌 Utilisateur récupéré : " + user.getNom() + " - " + user.getEmail()); // Debug
                    tableModel.addRow(new Object[]{
                        user.getIdUser(),
                        user.getNom(),
                        user.getPrenom(),
                        user.getEmail(),
                        user.getRole()
                    });
                }
            }

            // Ajout du tri et filtrage
            rowSorter = new TableRowSorter<>(tableModel);
            jTableUsers.setRowSorter(rowSorter);

            jTableUsers.revalidate();
            jTableUsers.repaint();

        } catch (Exception e) {
            System.out.println("❌ Erreur de chargement : " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur de chargement : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }


    
    private void rechercherUtilisateur() {
        String searchText = jTextFieldsearch.getText().trim();
        if (searchText.isEmpty()) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
        }
    }
    
    /**
     * Ajoute un nouvel utilisateur
     */
    private void ajouterUtilisateur() {
        new FormulaireUtilisateur(this, true, null).setVisible(true);
        chargerUtilisateurs();
    }

    /**
     * Modifie un utilisateur sélectionné
     */
    private void modifierUtilisateur() {
        int selectedRow = jTableUsers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un utilisateur à modifier.");
            return;
        }

        try {
            int id = Integer.parseInt(jTableUsers.getValueAt(selectedRow, 0).toString());
            Users user = usersCRUD.getUserById(id);

            if (user != null) {
                FormulaireUtilisateur form = new FormulaireUtilisateur(this, true, user);
                form.setVisible(true);
                chargerUtilisateurs();
            } else {
                JOptionPane.showMessageDialog(this, "Utilisateur introuvable.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Anonymise un utilisateur au lieu de le supprimer
     */
    private void supprimerUtilisateur() {
        int selectedRow = jTableUsers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un utilisateur à supprimer.");
            return;
        }

        try {
            int id = Integer.parseInt(jTableUsers.getValueAt(selectedRow, 0).toString());
            int confirm = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment anonymiser cet utilisateur ?", "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                boolean success = usersCRUD.anonymiserUtilisateur(id);

                if (success) {
                    JOptionPane.showMessageDialog(this, "Utilisateur anonymisé avec succès !");
                    chargerUtilisateurs();
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de l'anonymisation.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageAdmin(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JMenuItem itemClient;
    private javax.swing.JMenuItem itemStock;
    private javax.swing.JMenuItem itemVente;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnretour;
    private javax.swing.JLabel jLabelGestionCpt;
    private javax.swing.JMenu jMenuGerer;
    private javax.swing.JMenuBar jMenuGestion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextFieldsearch;
    private javax.swing.JButton jbtnConfigDB;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnQuitter;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JButton jbtnsearch;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
