/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vue;

import Modele.Stocks;
import crud.StockCRUD;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carmelle Adou
 */
public class PageStocksDesactives extends javax.swing.JDialog {
    private StockCRUD stockCRUD;
    /**
     * Creates new form PageStocksDesactives
     */
    public PageStocksDesactives(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.stockCRUD = new StockCRUD();
        chargerStocksDesactives();
        
        jBtnReactiver.addActionListener(evt -> reactiverStock());
        jBtnFermer.addActionListener(evt -> this.dispose());
    }
    
    private void chargerStocksDesactives() {
        try {
            List<Stocks> listeStocks = stockCRUD.getDisabledStocks();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (Stocks stock : listeStocks) {
                model.addRow(new Object[]{
                    stock.getIdStock(),
                    stock.getNomArticle(),
                    stock.getDescriptionArticle(),
                    stock.getQuantiteEnStock(),
                    stock.getSeuilMin(),
                    stock.getEtat()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des stocks désactivés : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reactiverStock() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un stock à réactiver.");
            return;
        }

        try {
            int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
            int confirm = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment réactiver ce stock ?", "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                boolean success = stockCRUD.reactiverStock(id);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Stock réactivé avec succès !");
                    chargerStocksDesactives(); // Recharge la liste des désactivés
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur : impossible de réactiver ce stock.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors de la réactivation du stock : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnReactiver = new javax.swing.JButton();
        jBtnFermer = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Description", "Seuil", "Quantite"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 10, 600, 240));

        jBtnReactiver.setText("Reactiver");
        getContentPane().add(jBtnReactiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jBtnFermer.setText("Fermer");
        getContentPane().add(jBtnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageStocksDesactives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageStocksDesactives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageStocksDesactives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageStocksDesactives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PageStocksDesactives dialog = new PageStocksDesactives(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFermer;
    private javax.swing.JButton jBtnReactiver;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
